name: "Run tests"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ${{ matrix.os }} # creates a matrix of jobs to run in parellel (required for non fail-fast)

    strategy:
      fail-fast: false # dont kill the other pipeline processes if one fails
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: 3.12
        enable-cache: true # cache python packages so uv doesnt re-download on each run

    - name: Install dependencies
      run: |
        uv sync --dev --locked

    - name: Test with pytest and coverage
      run: |
        uv run coverage run -m pytest -v
        uv run coverage report -m --fail-under=15
        uv run coverage xml